CREATE USER notd_api;
GRANT USAGE ON SCHEMA public TO notd_api;
GRANT INSERT, SELECT, UPDATE, DELETE ON tbl_token_transfers TO notd_api;
GRANT ALL ON SEQUENCE tbl_token_transfers_id_seq TO notd_api;
GRANT INSERT, SELECT, UPDATE ON tbl_token_metadatas TO notd_api;
GRANT ALL ON SEQUENCE tbl_token_metadatas_id_seq TO notd_api;
GRANT INSERT, SELECT, UPDATE ON tbl_collections TO notd_api;
GRANT ALL ON SEQUENCE tbl_collections_id_seq TO notd_api;
GRANT INSERT, SELECT, UPDATE ON tbl_blocks TO notd_api;
GRANT ALL ON SEQUENCE tbl_blocks_id_seq TO notd_api;
GRANT INSERT, SELECT, UPDATE ON tbl_token_ownerships TO notd_api;
GRANT ALL ON SEQUENCE tbl_token_ownerships_id_seq TO notd_api;
GRANT INSERT, SELECT, UPDATE, DELETE ON tbl_token_multi_ownerships TO notd_api;
GRANT ALL ON SEQUENCE tbl_token_multi_ownerships_id_seq TO notd_api;
GRANT INSERT, SELECT, UPDATE, DELETE ON tbl_collection_hourly_activity TO notd_api;
GRANT ALL ON SEQUENCE tbl_collection_hourly_activity_id_seq TO notd_api;
GRANT INSERT, SELECT ON tbl_user_interactions TO notd_api;
GRANT ALL ON SEQUENCE tbl_user_interactions_id_seq TO notd_api;
