name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-app:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Build docker image
        run: docker build --tag $DOCKER_IMAGE .
      - name: Push to container registry
        run: docker push $DOCKER_IMAGE
  deploy-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-api:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Build docker image
        run: docker build --tag $DOCKER_IMAGE .
      - name: Push to container registry
        run: docker push $DOCKER_IMAGE
  run-app:
    needs: deploy-app
    runs-on: ubuntu-latest
    env:
      NAME: nftoftheday-app
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-app:latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APIBOX_URL }}
          username: ${{ secrets.APIBOX_USER }}
          key: ${{ secrets.APIBOX_SSH_KEY }}
          port: ${{ secrets.APIBOX_PORT }}
          envs: DOCKER_IMAGE,NAME
          script_stop: true
          script: |
            url="nft.tokenhunt.io"
            docker pull ${DOCKER_IMAGE}
            docker stop ${NAME} && docker rm ${NAME} || true
            docker run \
                --name ${NAME} \
                --detach \
                --publish-all \
                --restart unless-stopped \
                --env NAME=${NAME} \
                --env VIRTUAL_HOST=${url} \
                --env LETSENCRYPT_HOST=${url} \
                --env-file ~/.${NAME}.vars \
                ${DOCKER_IMAGE}
  run-api:
    needs: deploy-api
    runs-on: ubuntu-latest
    env:
      NAME: nftoftheday-api
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-api:latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APIBOX_URL }}
          username: ${{ secrets.APIBOX_USER }}
          key: ${{ secrets.APIBOX_SSH_KEY }}
          port: ${{ secrets.APIBOX_PORT }}
          envs: DOCKER_IMAGE,NAME
          script_stop: true
          script: |
            url="notd-api.kibalabs.com"
            docker pull ${DOCKER_IMAGE}
            docker stop ${NAME} && docker rm ${NAME} || true
            docker run \
                --name ${NAME} \
                --detach \
                --publish-all \
                --restart unless-stopped \
                --env NAME=${NAME} \
                --env VIRTUAL_HOST=${url} \
                --env LETSENCRYPT_HOST=${url} \
                --env-file ~/.${NAME}.vars \
                ${DOCKER_IMAGE} './start-api.sh'
  run-worker:
    needs: deploy-api
    runs-on: ubuntu-latest
    env:
      NAME: nftoftheday-worker
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-api:latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WORKERBOX_URL }}
          username: ${{ secrets.WORKERBOX_USER }}
          key: ${{ secrets.WORKERBOX_SSH_KEY }}
          port: ${{ secrets.WORKERBOX_PORT }}
          envs: DOCKER_IMAGE,NAME
          script_stop: true
          script: |
            docker pull ${DOCKER_IMAGE}
            docker stop ${NAME} && docker rm ${NAME} || true
            docker run \
                --name ${NAME} \
                --detach \
                --restart unless-stopped \
                --env NAME=${NAME} \
                --env-file ~/.${NAME}.vars \
                ${DOCKER_IMAGE} './start-worker.sh'
  run-worker-2:
    needs: deploy-api
    runs-on: ubuntu-latest
    env:
      NAME: nftoftheday-worker
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-api:latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APIBOX_URL }}
          username: ${{ secrets.APIBOX_USER }}
          key: ${{ secrets.APIBOX_SSH_KEY }}
          port: ${{ secrets.APIBOX_PORT }}
          envs: DOCKER_IMAGE,NAME
          script_stop: true
          script: |
            docker pull ${DOCKER_IMAGE}
            docker stop ${NAME} && docker rm ${NAME} || true
            docker run \
                --name ${NAME} \
                --detach \
                --restart unless-stopped \
                --env NAME=${NAME} \
                --env-file ~/.${NAME}.vars \
                ${DOCKER_IMAGE} './start-worker.sh'
